### ISSUE TITLE
Potential license issue with MPIRE[dill] being under a BSD license

### ISSUE THREAD

**Issue by bhavnicksm** [umarbutler/semchunk#13]
Hey @umarbutler, 

I preface this with a "I might be wrong about this, so correct me if I am", but according the MPIRE documentation the installation `mpire[dill]` would be under BSD license and hence, `semchunk` would also be under BSD license as required by it. 

Source: https://sybrenjansen.github.io/mpire/v2.3.0/install.html#dill

<img width="786" alt="image" src="https://github.com/user-attachments/assets/63386844-8b26-4b44-8eb7-a9b5c15eacad" />

If this is accurate, then it would be preferable not to use `mpire[dill]` as a default dependency in `semchunk`

Thanks! 😊

**Comment by umarbutler** [comment]
Hey @bhavnicksm, thanks for flagging this, I appreciate your due diligence.

I was actually already aware of the disclaimer you reference in `mpire`'s documentation.

Nevertheless, `semchunk` does not need to be licensed under the BSD license, even if it depends on `mpire[dill]`.

If we take a look at the disclaimer, we see that it states `pip install mpire[dill]` will `install [multiprocess](https://github.com/uqfoundation/multiprocess), which uses dill under the hood`. It also helpfully links to the license for `multiprocess` available [here](https://github.com/uqfoundation/multiprocess/blob/master/LICENSE). For the avoidance of doubt, that license is the same as the license for [`dill`](https://github.com/uqfoundation/dill/blob/master/LICENSE).

The license begins by stating that the provided software is licensed under its terms. It then lists three requirements for use of the software and finally disclaims warranties and liability.

What is relevant to us are the requirements for use of licensed software:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

    - Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

    - Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

    - Neither the names of the copyright holders nor the names of any of
      the contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
```

Points 3 and 2 are not relevant to `semchunk`. I do not use the names of any of the copyright holders or contributors to either `multiprocess` or `dill` anywhere in my documentation, let alone indicate that they endorse or promote any derivations of their software. Additionally, `semchunk` is not distributed as a binary (you can verify that by opening the wheels on [PyPI](https://pypi.org/project/semchunk/#files) as zip files 😊) and even if it was, point 2 would only really apply if I also included `multiprocess` or `dill` inside the binary.

Point 1 is also not relevant to `semchunk`. `semchunk` does not redistribute the source code of either `multiprocess` or `dill`.

To be sure, `semchunk` _uses_ `multiprocess` or `dill`, but it still requires both of those packages to be installed to be useable. I do not distribute those packages with `semchunk`. When you `pip install semchunk`, `pip` downloads `multiprocess` and `dill` if they are not already installed. But all that I am distributing is the source code for `semchunk`.

Finally, `dill` and `multiprocess` already retain copyright licenses for their code. So if it was the case that I was redistributing `multiprocess` and `dill`, point 1 would still be satisfied.

The only scenario where point 1 wouldn't be satisfied is if I had decided to directly copy the source code of `multiprocess` or `dill` into `semchunk` and then strip out the copyright licenses. Or if I offered `semchunk` binaries that included `multiprocess` and `dill` directly inside of them, and I didn't share their copyright license.

BSD is a permissive copyright license, much like MIT. It is not a copyleft or viral license like GPL. It does not purport to impose additional terms on works that rely on material it covers.

So there is no scenario where it is possible that the entirety of `semchunk` could be covered by BSD. At 'worst', there would be a dual license, BSD for the portion of any code packaged inside `semchunk` that is licensed under BSD, and then whatever I want for my own code.

As for why `mpire` claims that it becomes licensed under BSD if `dill` is installed? I'm honestly not too sure 😆 Maybe `mpire[dill]` actually includes source code from `multiprocess` and `dill` inside of it? But even then, that shouldn't apply virally to the rest of their source code.

**Comment by bhavnicksm** [comment]
I see, that makes sense~ thanks for clarifying! 😄
