### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by jcobol** [umarbutler/semchunk#4]
It is possible for a token counter to return zero tokens, leading to a division by zero error in the `merge_splits` function:
```
  File "C:\Users\user\miniconda3\envs\project\Lib\site-packages\semchunk\semchunk.py", line 78, in merge_splits
    average = cumulative_lengths[midpoint] / tokens if cumulative_lengths[midpoint] else average
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
ZeroDivisionError: division by zero
```

**Comment by umarbutler** [comment]
Thanks for this! This bug is now fixed in [v0.3.2](https://github.com/umarbutler/semchunk/releases/tag/v0.3.2) :)
