### ISSUE TITLE
Add support for outputting start and end indices of chunks

### ISSUE THREAD

**Issue by umarbutler** [umarbutler/semchunk#9]
It would be convenient to be able to output the start and end indices of chunks. I will work on this soon.

**Comment by bhavnicksm** [comment]
Hey @umarbutler!

[Chonkie](https://github.com/chonkie-ai/chonkie) get's start and end indices of the chunks~ Not sure if it helps, but have a look!

Thanks 😊

**Comment by umarbutler** [comment]
@bhavnicksm I actually already finished this feature yesterday, there’s just some other stuff I’m packing into the next release, but it should be out soon!

**Comment by umarbutler** [comment]
This is done in version 3.0.0.
